# MATH630 Programming Assignment#3
Prem Kaushyk Premsiva (pp6@njit.edu)

In [4]:
import numpy as np

In [5]:
def row_exchange(A,row_i,row_j):
  
  A[[row_i,row_j]] = A[[row_j,row_i]]

  return A

In [6]:
def row_scale(A,row_i,scaler):

  A[[row_i]]= scaler* A[[row_i]]
  
  return A

In [7]:
def row_eliminate(A,row_i,row_j,x):

  A[[row_j]] = A[[row_j]] + x*A[[row_i]]
  
  return A

In [9]:
def linear_equation_solver(A,b):

    A = A.astype(np.float32)
    b = b.reshape(b.shape[1],1).astype(np.float32)                
    m,n = A.shape
    xp = np.zeros(n,float)
    free_col=[]
    pivot_col=[]

    #Reduced Row Echelon Form
    cur_row = cur_col = 0
    while cur_row < m and cur_col < n:    
        pivot = -1
        for i, val in enumerate(A[cur_row:,cur_col]):    
            if val!= 0 :
                pivot = cur_row + i
                pivot_col.append(cur_col)      #Recording pivot columns                 
                break 
        if pivot < 0 :
            free_col.append(cur_col)           #Recording free columns
            cur_col += 1       

        else:
            if pivot != cur_row:           
                A = row_exchange(A,cur_row,pivot)
                b = row_exchange(b,cur_row,pivot)
                
            for row_k in range(cur_row+1, m):
                if abs(A[row_k, cur_col]) > abs(A[cur_row, cur_col]):         #Partial Pivoting
                  A = row_exchange(A, cur_row, row_k )
                  b = row_exchange(b, cur_row, row_k)

            scaler = A[cur_row,cur_col]
            A = row_scale(A,cur_row,(1/(scaler)))
            b = row_scale(b,cur_row,(1/(scaler)))      

            for row_k in range(m):

                if row_k == cur_row: continue

                x = -A[row_k, cur_col] / A[cur_row, cur_col]
                A = row_eliminate(A, cur_row, row_k, x)
                b = row_eliminate(b, cur_row, row_k, x)

            cur_row += 1
            cur_col += 1
    print("REDUCED ROW ECHELON FORM of given matrix ")
    print(A)
    print(b)
            
    #Solving for the particular and Homogeneous solutions
    xp = np.zeros(n,float)
    xh = []

    cur_row = cur_col = 0                #Reassign pointers

    while cur_row < m and cur_col < n:

          zero_row = np.all((A==0), axis = 1)     #Checking for 'No solution'
          for row_i in range(len(zero_row)):
              if zero_row[row_i] and b[row_i]!=0: 
                return('No Solution')
          

          if cur_col in pivot_col:
              xp[cur_col] = b[cur_row]        
              cur_row+=1
        
          if cur_col in free_col:
              xhi = np.zeros(n,float)     #Homogeneous vectors
              
              for i in range(0,cur_row):
                  xhi[i] = -1 * A[i,cur_col] 
                  xhi[cur_col] = 1
              xh.append(xhi)

          cur_col+=1

    print(xp) #Particular Solution
    print(xh) #Homogeneous Solution

In [10]:
#Example_1

A = np.matrix([[ -1,  1,  2, -8,  16,   30 ],
      [ 4, -4, -8, 28, -60, -108 ],
      [ 1, -1, -2,  0, -12,  -10 ],
      [ 4, -4, -8, 24, -60, -100 ]])

b = np.matrix([-89,328,49,316])

linear_equation_solver(A,b)

REDUCED ROW ECHELON FORM of given matrix 
[[ 1. -1. -2.  0.  0.  2.]
 [-0. -0. -0.  1.  0. -2.]
 [-0. -0. -0. -0.  1.  1.]
 [ 0.  0.  0.  0.  0.  0.]]
[[ 1.]
 [ 3.]
 [-4.]
 [ 0.]]
[ 1.  0.  0.  3. -4.  0.]
[array([1., 1., 0., 0., 0., 0.]), array([2., 0., 1., 0., 0., 0.]), array([-2.,  2., -1.,  0.,  0.,  1.])]


In [12]:
#Example_2

A = np.matrix([[2,2,2,4,-12], 
               [0,0,0,-2,4], 
               [0,0,0,4,-8]])

b = np.matrix([4,-4,8])

linear_equation_solver(A,b)

REDUCED ROW ECHELON FORM of given matrix 
[[ 1.  1.  1.  0. -2.]
 [ 0.  0.  0.  1. -2.]
 [ 0.  0.  0.  0.  0.]]
[[-2.]
 [ 2.]
 [ 0.]]
[-2.  0.  0.  2.  0.]
[array([-1.,  1.,  0.,  0.,  0.]), array([-1.,  0.,  1.,  0.,  0.]), array([2., 2., 0., 0., 1.])]


In [13]:
#Midterm Question:

A = np.matrix([[1,2,0,-2,1,-4], 
               [0,0,0,0,1,-2], 
               [1,2,0,-2,1,-4],
               [-2,-4,1,3,-2,10], 
               [-2,-4,0,4,-2,8]])

b = np.matrix([0,-1,0,2,0])

linear_equation_solver(A,b)

REDUCED ROW ECHELON FORM of given matrix 
[[ 1.  2.  0. -2.  0. -2.]
 [ 0.  0.  1. -1.  0.  2.]
 [ 0.  0.  0.  0.  1. -2.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
[[ 1.]
 [ 2.]
 [-1.]
 [ 0.]
 [ 0.]]
[ 1.  0.  2.  0. -1.  0.]
[array([-2.,  1.,  0.,  0.,  0.,  0.]), array([2., 1., 0., 1., 0., 0.]), array([ 2., -2.,  2.,  0.,  0.,  1.])]


In [14]:
#Example_4 (No solution)

A = np.matrix([[ -1,  1,  2, -8,  16,   30 ],
      [ 4, -4, -8, 28, -60, -108 ],
      [ 1, -1, -2,  0, -12,  -10 ],
      [ 4, -4, -8, 24, -60, -100 ]])

b = np.matrix([-89,328,49,317])

linear_equation_solver(A,b)

REDUCED ROW ECHELON FORM of given matrix 
[[ 1. -1. -2.  0.  0.  2.]
 [-0. -0. -0.  1.  0. -2.]
 [-0. -0. -0. -0.  1.  1.]
 [ 0.  0.  0.  0.  0.  0.]]
[[-6.       ]
 [ 2.75     ]
 [-4.5833335]
 [ 0.3333335]]


'No Solution'